resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 5
        eventConsumerBufferSize: 10

  retry:
    instances:
      userServiceRetry:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.io.IOException
          - java.net.ConnectException

  timelimiter:
    instances:
      userServiceTimeout:
        timeoutDuration: 5s
