resilience4j:
  circuitbreaker:
    instances:
      courseServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5

  retry:
    instances:
      courseServiceRetry:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.net.ConnectException
          - java.io.IOException

  timelimiter:
    instances:
      courseServiceTimeout:
        timeoutDuration: 3s
