routes:
  - id: user-service
    uri: lb://USER-SERVICE
    predicates:
      - Path=/users/**
      - Path=/auth/**
    filters:
      - CircuitBreaker=name=userServiceCB,fallbackUri=/fallback/user
      - Retry=name=userServiceRetry,maxAttempts=3,waitDuration=1000ms
      - RequestTimeout=timeout=5000ms

  - id: course-service
    uri: lb://COURSE-SERVICE
    predicates:
      - Path=/courses/**
    filters:
      - CircuitBreaker=name=courseServiceCB,fallbackUri=/fallback/course
      - Retry=name=courseServiceRetry,maxAttempts=3,waitDuration=1000ms
      - RequestTimeout=timeout=5000ms

  - id: payment-service
    uri: lb://PAYMENT-SERVICE
    predicates:
      - Path=/payment/**
    filters:
      # - StripPrefix=1               # removes "/payment" before forwarding
      - CircuitBreaker=name=paymentServiceCB,fallbackUri=/fallback/payment

  - id: assessment-service
    uri: lb://ASSESSMENT-SERVICE
    predicates:
      - Path=/tests/**
    filters:
      - CircuitBreaker=name=assessmentServiceCB,fallbackUri=/fallback/assessment
      - Retry=name=assessmentServiceRetry,maxAttempts=3,waitDuration=1000ms
      - RequestTimeout=timeout=5000ms
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG