server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: default
            fallbackUri: forward:/fallback
      routes:
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/courses/**
          filters:
            - JwtAuthFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**, /auth/**
          filters:
            - JwtAuthFilter

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
            - JwtAuthFilter

        - id: assessment-service
          uri: lb://ASSESSMENT-SERVICE
          predicates:
            - Path=/assessments/**
          filters:
            - JwtAuthFilter

  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
