server:
  port: 8080

spring:
  application:
    name: gateway-service

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - CircuitBreaker=name=userServiceCB,fallbackUri=/fallback/user
            - Retry=name=userServiceRetry,maxAttempts=3,waitDuration=1000ms
            - RequestTimeout=timeout=5000ms

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**
          filters:
            - CircuitBreaker=name=courseServiceCB,fallbackUri=/fallback/course
            - Retry=name=courseServiceRetry,maxAttempts=3,waitDuration=1000ms
            - RequestTimeout=timeout=5000ms

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - CircuitBreaker=name=paymentServiceCB,fallbackUri=/fallback/payment
            - Retry=name=paymentServiceRetry,maxAttempts=3,waitDuration=1000ms
            - RequestTimeout=timeout=5000ms

        - id: assessment-service
          uri: lb://assessment-service
          predicates:
            - Path=/assessments/**
          filters:
            - CircuitBreaker=name=assessmentServiceCB,fallbackUri=/fallback/assessment
            - Retry=name=assessmentServiceRetry,maxAttempts=3,waitDuration=1000ms
            - RequestTimeout=timeout=5000ms


  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
