 # harmless on Windows; keeps hostname consistent


spring:
  application:
    name: PAYMENT-SERVICE

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:                
    prefer-ip-address: true
    ip-address: 127.0.0.1   
    # hostname: localhost    
  # instance:
  #   prefer-ip-address: true      

# -------- Resilience4j --------
resilience4j:
  circuitbreaker:
    instances:
      userServiceCB:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        registerHealthIndicator: true

  retry:
    instances:
      userServiceRetry:
        maxAttempts: 3
        waitDuration: 1s

  timelimiter:
    instances:
      userServiceTimeout:
        timeoutDuration: 4s
